# Generated by Django 2.2.16 on 2022-07-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220720_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='data',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Картинка'),
        ),
    ]
