# Generated by Django 3.2.14 on 2022-07-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220731_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
