# Generated by Django 3.2.14 on 2022-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_delete_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#CCCCCC', max_length=7, unique=True, verbose_name='Цвет'),
        ),
    ]
