# Generated by Django 2.2.16 on 2022-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220727_2127'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shopping_cart',
            name='unique purchase',
        ),
        migrations.RenameField(
            model_name='shopping_cart',
            old_name='purchase',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='shopping_cart',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique shopping cart'),
        ),
    ]
