# Generated by Django 3.2.14 on 2022-07-30 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_ingredient_recipes_ing_name_164c6a_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date']},
        ),
    ]
